# Generated by Django 4.1.7 on 2023-02-21 07:56

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_video_text_image_file_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="content",
            name="order",
            field=core.fields.OrderField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=core.fields.OrderField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
