# Generated by Django 4.1.7 on 2023-04-21 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_author_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.ForeignKey(
                null="True",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.level",
            ),
            preserve_default="True",
        ),
    ]
