# Generated by Django 4.1.7 on 2023-05-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_what_you_learn_requriments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Requriments",
            new_name="Requirements",
        ),
    ]
