# Generated by Django 4.1.7 on 2023-02-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_content_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Subject",
            new_name="subject",
        ),
    ]
