# Generated by Django 4.1.7 on 2023-05-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_lesson_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="time_duration",
            field=models.IntegerField(null=True),
        ),
    ]
