# Generated by Django 4.1.7 on 2023-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_language_course_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="certificate",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="deadline",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
