# Generated by Django 4.1.7 on 2023-05-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_course_certificate_course_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="certificate",
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
